# SPDX-License-Identifier: MIT
"""Role-rewriting reverse proxy for OpenAI-compatible Responses API targets.

Why this exists: Codex 0.125+ sends Responses-API requests with
`role: "developer"` messages (the OpenAI standard). Some self-hosted
chat templates (e.g. Qwen 3.6) only know the legacy roles
`{system, user, assistant, tool}` and reject `developer` with HTTP 400.
This shim sits between Codex and the upstream, rewriting
`developer` → `system` inside POST `/v1/responses` request bodies and
passing everything else through unchanged. It is a benchmark-side
adapter, not a long-term fix; the proper solution lives in the
model-side chat template.

Out of scope: auth, rate limiting, multi-target routing, schema
translation between Responses ↔ Chat Completions. The proxy is a thin
passthrough.
"""

from __future__ import annotations

import json
from typing import Any

import aiohttp
from aiohttp import web

# Headers we strip from the inbound request before forwarding because
# they will be regenerated by aiohttp for the new outbound request.
# Leaving them in causes content-length/transfer-encoding mismatches
# when the body has been mutated by the role rewrite.
_HOP_BY_HOP = frozenset(
    h.lower()
    for h in (
        "host",
        "content-length",
        "transfer-encoding",
        "connection",
        "keep-alive",
        "proxy-authenticate",
        "proxy-authorization",
        "te",
        "trailers",
        "upgrade",
    )
)

UPSTREAM_BASE: web.AppKey[str] = web.AppKey("upstream_base", str)
TIMEOUT_S: web.AppKey[float] = web.AppKey("timeout_s", float)


def _extract_text(content: object) -> list[str]:
    """Pull every text fragment out of a Responses-API ``content`` field.

    The field is either a string or a list of typed parts (``input_text``,
    ``text``, etc.) — both shapes are flattened to a list of plain strings.
    """
    if isinstance(content, str):
        return [content] if content else []
    if not isinstance(content, list):
        return []
    out: list[str] = []
    for part in content:
        if isinstance(part, dict):
            text = part.get("text") or part.get("input_text") or ""
            if isinstance(text, str) and text:
                out.append(text)
    return out


def _rewrite_responses_body(raw: bytes) -> bytes:
    """Move every developer/system message in ``input[]`` into ``instructions``.

    Codex 0.125+ sends a Responses request whose ``input`` array begins with
    a ``developer`` message (its agent prompt), but vLLM's Responses adapter
    *also* renders the top-level ``instructions`` field as a system message.
    With both sources present the chat template ends up with multiple system
    messages and Qwen 3.6 rejects 400 ("System message must be at the
    beginning"). Keeping the role ``developer`` is also rejected outright.

    The fix: concatenate every ``developer``/``system`` message's text into
    the ``instructions`` string and drop those entries from ``input``. The
    forwarded request now has exactly one logical system source
    (``instructions``) and an ``input`` array of only ``user``/``assistant``
    turns, which the chat template renders correctly.

    Preserves the body byte-for-byte if it isn't valid JSON, doesn't have an
    ``input: [...]`` array, or doesn't contain any system-like messages — the
    upstream surfaces schema errors more clearly than this shim ever could.
    """
    if not raw:
        return raw
    try:
        obj: Any = json.loads(raw)
    except json.JSONDecodeError:
        return raw
    if not isinstance(obj, dict):
        return raw
    inp = obj.get("input")
    if not isinstance(inp, list):
        return raw

    system_chunks: list[str] = []
    kept: list[Any] = []
    for msg in inp:
        if isinstance(msg, dict) and msg.get("role") in ("developer", "system"):
            system_chunks.extend(_extract_text(msg.get("content")))
        else:
            kept.append(msg)

    existing = obj.get("instructions")
    if existing is not None and not isinstance(existing, str):
        return raw

    merged = existing or ""
    for chunk in system_chunks:
        if merged:
            merged += "\n\n"
        merged += chunk

    # Force tool calls off. The harness measures CLI throughput, not
    # agentic tool execution. Without this codex sees its 11 declared
    # tools, decides the prompt warrants reading a file, calls
    # exec_command, and the second-turn request body that codex sends
    # back contains ``function_call``/``function_call_output`` items
    # that vLLM's Responses-adapter rejects with 215 pydantic errors
    # ("Input should be a valid string"). Setting tool_choice="none"
    # and tools=[] stops the loop before it starts.
    needs_tool_off = obj.get("tool_choice") != "none" or obj.get("tools") not in (None, [])
    if not system_chunks and not needs_tool_off:
        return raw

    obj["instructions"] = merged
    obj["input"] = kept
    obj["tool_choice"] = "none"
    obj["tools"] = []
    return json.dumps(obj).encode("utf-8")


def _rewrite_chat_completions_body(raw: bytes) -> bytes:
    """Force tool calls off in a Chat-Completions request body.

    OpenCode talks /v1/chat/completions directly. With its built-in tools
    (bash/edit/grep/...) advertised, qwen3.6 invokes them on the synthetic
    code-dump prompts and OpenCode loops on tool-execution turns until the
    session_timeout fires (2026-04-29 mi250-069 4-concurrent smoke: 100%
    timeouts at 600 s). Stripping ``tools`` and pinning ``tool_choice`` to
    ``"none"`` here guarantees the model can't initiate a tool call no
    matter what the client declared.

    Preserves the body byte-for-byte if it isn't valid JSON, isn't a JSON
    object, or already has tools off — the upstream surfaces schema errors
    more clearly than this shim ever could.
    """
    if not raw:
        return raw
    try:
        obj: Any = json.loads(raw)
    except json.JSONDecodeError:
        return raw
    if not isinstance(obj, dict):
        return raw
    if obj.get("tool_choice") == "none" and obj.get("tools") in (None, []):
        return raw
    obj["tool_choice"] = "none"
    obj["tools"] = []
    return json.dumps(obj).encode("utf-8")


async def _proxy_handler(request: web.Request) -> web.StreamResponse:
    upstream_base = request.app[UPSTREAM_BASE]
    timeout_s = request.app[TIMEOUT_S]

    body = await request.read()
    if request.method == "POST" and request.path == "/v1/responses":
        body = _rewrite_responses_body(body)
    elif request.method == "POST" and request.path == "/v1/chat/completions":
        body = _rewrite_chat_completions_body(body)

    forwarded_headers = {k: v for k, v in request.headers.items() if k.lower() not in _HOP_BY_HOP}

    target = upstream_base.rstrip("/") + request.rel_url.path_qs
    timeout = aiohttp.ClientTimeout(total=timeout_s)

    async with aiohttp.ClientSession(timeout=timeout) as session:
        async with session.request(
            request.method,
            target,
            headers=forwarded_headers,
            data=body if body else None,
        ) as upstream:
            resp_headers = {
                k: v for k, v in upstream.headers.items() if k.lower() not in _HOP_BY_HOP
            }
            resp = web.StreamResponse(status=upstream.status, headers=resp_headers)
            await resp.prepare(request)
            async for chunk in upstream.content.iter_chunked(8192):
                await resp.write(chunk)
            await resp.write_eof()
            return resp


def make_app(upstream_base: str, timeout_s: float = 600.0) -> web.Application:
    """Build the aiohttp app. `upstream_base` is the URL prefix the proxy
    forwards every request to (e.g. `http://127.0.0.1:18000`). `timeout_s`
    is the per-request total timeout for the upstream call."""
    app = web.Application()
    app[UPSTREAM_BASE] = upstream_base
    app[TIMEOUT_S] = timeout_s
    app.router.add_route("*", "/{path:.*}", _proxy_handler)
    return app
