# SPDX-License-Identifier: MIT
"""Role-rewriting reverse proxy for OpenAI-compatible Responses API targets.

Why this exists: Codex 0.125+ sends Responses-API requests with
`role: "developer"` messages (the OpenAI standard). Some self-hosted
chat templates (e.g. Qwen 3.6) only know the legacy roles
`{system, user, assistant, tool}` and reject `developer` with HTTP 400.
This shim sits between Codex and the upstream, rewriting
`developer` → `system` inside POST `/v1/responses` request bodies and
passing everything else through unchanged. It is a benchmark-side
adapter, not a long-term fix; the proper solution lives in the
model-side chat template.

Out of scope: auth, rate limiting, multi-target routing, schema
translation between Responses ↔ Chat Completions. The proxy is a thin
passthrough.
"""

from __future__ import annotations

import json
from typing import Any

import aiohttp
from aiohttp import web

# Headers we strip from the inbound request before forwarding because
# they will be regenerated by aiohttp for the new outbound request.
# Leaving them in causes content-length/transfer-encoding mismatches
# when the body has been mutated by the role rewrite.
_HOP_BY_HOP = frozenset(
    h.lower()
    for h in (
        "host",
        "content-length",
        "transfer-encoding",
        "connection",
        "keep-alive",
        "proxy-authenticate",
        "proxy-authorization",
        "te",
        "trailers",
        "upgrade",
    )
)

UPSTREAM_BASE: web.AppKey[str] = web.AppKey("upstream_base", str)
TIMEOUT_S: web.AppKey[float] = web.AppKey("timeout_s", float)


def _rewrite_responses_body(raw: bytes) -> bytes:
    """Rewrite developer→system roles inside a Responses-API request body.

    Preserves the body byte-for-byte if it isn't valid JSON or if it
    doesn't have the expected `input: [...]` shape — the upstream will
    surface schema errors more clearly than this shim ever could.
    """
    if not raw:
        return raw
    try:
        obj: Any = json.loads(raw)
    except json.JSONDecodeError:
        return raw
    if not isinstance(obj, dict):
        return raw
    inp = obj.get("input")
    if not isinstance(inp, list):
        return raw
    mutated = False
    for msg in inp:
        if isinstance(msg, dict) and msg.get("role") == "developer":
            msg["role"] = "system"
            mutated = True
    if not mutated:
        return raw
    return json.dumps(obj).encode("utf-8")


async def _proxy_handler(request: web.Request) -> web.StreamResponse:
    upstream_base = request.app[UPSTREAM_BASE]
    timeout_s = request.app[TIMEOUT_S]

    body = await request.read()
    if request.method == "POST" and request.path == "/v1/responses":
        body = _rewrite_responses_body(body)

    forwarded_headers = {k: v for k, v in request.headers.items() if k.lower() not in _HOP_BY_HOP}

    target = upstream_base.rstrip("/") + request.rel_url.path_qs
    timeout = aiohttp.ClientTimeout(total=timeout_s)

    async with aiohttp.ClientSession(timeout=timeout) as session:
        async with session.request(
            request.method,
            target,
            headers=forwarded_headers,
            data=body if body else None,
        ) as upstream:
            resp_headers = {
                k: v for k, v in upstream.headers.items() if k.lower() not in _HOP_BY_HOP
            }
            resp = web.StreamResponse(status=upstream.status, headers=resp_headers)
            await resp.prepare(request)
            async for chunk in upstream.content.iter_chunked(8192):
                await resp.write(chunk)
            await resp.write_eof()
            return resp


def make_app(upstream_base: str, timeout_s: float = 600.0) -> web.Application:
    """Build the aiohttp app. `upstream_base` is the URL prefix the proxy
    forwards every request to (e.g. `http://127.0.0.1:18000`). `timeout_s`
    is the per-request total timeout for the upstream call."""
    app = web.Application()
    app[UPSTREAM_BASE] = upstream_base
    app[TIMEOUT_S] = timeout_s
    app.router.add_route("*", "/{path:.*}", _proxy_handler)
    return app
